#!/bin/bash
# export-store-lan.sh — 从 Store/ 导出扁平 LAN 仓库（PR-LAN-store-0 / store-src）
#
# 产出目录可直接:
#   cd <out> && python3 -m http.server 8080
# Guest: store repo <台式机IP>:8080 → sync / install
#
# 用法:
#   ./Tools/Scripts/export-store-lan.sh [out-dir]
# 默认 out-dir = Build/store-lan（gitignore）
#
# 首期：只拷 catalog 的 file= 字段（单文件课包）；不递归拷 packages/*/Assets。
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

# 货架真源在 ToyImage/Store（Image 阶段）；可用 STORE_SRC 覆盖
StoreSrc="${STORE_SRC:-../ToyImage/Store}"
Catalog="$StoreSrc/catalog.txt"
Out="${1:-Build/store-lan}"

if [ ! -f "$Catalog" ]; then
    echo "error: missing $Catalog" >&2
    exit 1
fi

mkdir -p "$Out"
# 干净重导：只清文件，保留目录
find "$Out" -mindepth 1 -maxdepth 1 -type f -delete 2>/dev/null || true

cp -f "$Catalog" "$Out/catalog.txt"

Copied=0
Missing=0
Skipped=0

while IFS= read -r Line || [ -n "$Line" ]; do
    Line="${Line%$'\r'}"
    case "$Line" in
        ''|'#'*) continue ;;
    esac
    # id|type|version|file|sha256|arch|title[|depends]
    IFS='|' read -r Id Type Ver File Sha Arch Title Depends <<EOF
$Line
EOF
    unset Type Ver Sha Arch Title Depends
    if [ -z "${Id:-}" ] || [ -z "${File:-}" ]; then
        echo "warn: bad catalog line: $Line" >&2
        Skipped=$((Skipped + 1))
        continue
    fi
    Src=""
    if [ -f "$StoreSrc/packages/$Id/$File" ]; then
        Src="$StoreSrc/packages/$Id/$File"
    fi
    if [ -z "$Src" ]; then
        echo "warn: missing packages/$Id/$File (skip id=$Id)" >&2
        Missing=$((Missing + 1))
        continue
    fi
    cp -f "$Src" "$Out/$File"
    Copied=$((Copied + 1))
done < "$Catalog"

cat > "$Out/README.txt" <<EOF
ToyOS LAN store tree (PR-LAN-store-src)
Generated by Tools/Scripts/export-store-lan.sh

Desktop:
  cd $(basename "$Out")   # or full path
  python3 -m http.server 8080
  # if ufw: sudo ufw allow 8080/tcp
  # LAN IP: ip -4 addr

NUC (ToyOS Shell):
  lwip dhcp
  ping <DESKTOP_IP>
  store repo <DESKTOP_IP>:8080
  store sync
  store install hello
  exec Apps/hello/HELLO.ELF
  # CHAT-4 闭环（镜像不预装 chat）：
  store install chat
  dbset chat.peer <DESKTOP_IP>
  exec Apps/chat/CHAT.ELF

QEMU unchanged: default store.repo=10.0.2.2:8080
See Documents/开发/局域网商店与聊天.md
EOF

echo "export-store-lan: $Copied file(s) -> $Out/"
echo "  catalog.txt + README.txt written"
if [ "$Missing" -gt 0 ]; then
    echo "  warn: $Missing missing payload(s)" >&2
fi
if [ "$Skipped" -gt 0 ]; then
    echo "  warn: $Skipped bad line(s)" >&2
fi
if [ "$Copied" -lt 1 ]; then
    echo "error: no payloads copied" >&2
    exit 1
fi
ls -la "$Out"
